### ISSUE TITLE
Switch direction of change

### ISSUE THREAD

**Issue by henningbuddenbaum** [davidfrantz/hungry-beetle#1]
For some indices, a disturbance is shown by lower-than-expected values, for other indices, it's higher-than-expected values.
The code should get a switch to adapt to the direction of the selected spectral index.
In my case, the results for 'CRemoveSWIR1' and 'CIre' are contrarian.

**Comment by davidfrantz** [comment]
new parameter in beetle.config:

```
  /* threshold test direction: gt = +1 | lt = -1 */
  thr_direction = 1
```
